version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  apache:
    build: apache/.
    container_name: apache
    image: apache
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "apache:/var/www/html"
  elasticsearch:
    build: elasticsearch/.
    container_name: elasticsearch
    image: elasticsearch
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  liferay:
    build:
      args:
        LIFERAY_HOME: /usr/local/liferay-dxp-digital-enterprise-7.0-sp6
        LIFERAY_TOMCAT_URL: http://mirrors/files.liferay.com/private/ee/portal/7.0.10.6/liferay-dxp-digital-enterprise-tomcat-7.0-sp6-20171010144253003.zip
        WORKSPACE_DIR: /tmp/www-workspace-master
        WORKSPACE_URL: https://github.com/ryanschuhler/www-workspace/archive/master.zip
      context: liferay/.
    container_name: liferay
    depends_on:
     - "mariadb"
    environment:
      - "VIRTUAL_PORT=8080"
    image: liferay
    networks:
      - "www-external"
      - "www-internal"
    volumes:
      - "liferay:/opt/liferay/home/data"
  mariadb:
    build:
      args:
        DB_URL: http://mirrors/files.liferay.com/private/lrdcom/www_lportal-2017-11-27_19-00-PST.sql.gz
      context: mariadb/.
    container_name: mariadb
    environment:
      - "MYSQL_DATABASE=lportal"
      - "MYSQL_ROOT_PASSWORD=passw0rd"
      - "character-set-server=utf8mb4"
      - "collation-server=utf8mb4_unicode_ci"
    image: mariadb
    networks:
      - "www-internal"
    volumes:
      - "mariadb:/var/lib/mysql"
  mockmock:
    build: mockmock/.
    container_name: mockmock
    expose:
      - "25"
    image: mockmock
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8282:8282"
    volumes:
      - "mockmock:/home"

volumes:
  apache:
  elasticsearch:
  liferay:
  mariadb:
  mockmock: